/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * form1.java
 *
 * Created on Dec 31, 2013, 7:21:41 PM
 */
package lat1;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author asus
 */
public class form1 extends javax.swing.JFrame {

    public Connection conn;
    public Statement stat;
    
    public void koneksi(){
        try{
            Class.forName("com.jdbc.mysql.driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_java","root","");
            stat = conn.createStatement();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"KOneksi Gagal");
            System.out.println(e.getMessage());
            
        }
            
    }
    
    /** Creates new form form1 */
    public form1() {
        initComponents();
        setLocationRelativeTo(null);
                 //setLocationRelativeTo(null);// membuat form ditengah

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setLabel("Test Koneksi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton1)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(135, 135, 135))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        koneksi();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new form1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
