/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * form2.java
 *
 * Created on Dec 31, 2013, 10:45:09 PM
 */
package lat1;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;


/**
 *
 * @author asus
 */
public class form2 extends javax.swing.JFrame {

    public Connection conn;
    public Statement stat;
    //membuat koneksi
    public void koneksi(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_java","root","");
            stat = conn.createStatement();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Koneksi Gagal");
            System.out.println(e.getMessage());
        }
    }
    
    public void kosong(){
        txtkode.setText("");
        txtnama.setText("");
        txtbagian.setText("");
    }
    
    public void aktif(){
        txtkode.setEnabled(true);
        txtnama.setEnabled(true);
        txtbagian.setEnabled(true);
    }
    
    public void nonaktif(){
        txtkode.setEnabled(false);
        txtnama.setEnabled(false);
        txtbagian.setEnabled(false);
    }
    
    public void tampil_data(){
            DefaultTableModel tabelnya = new DefaultTableModel();
            tabelnya.addColumn("Kode karyawan");
            tabelnya.addColumn("Nama Karyawan");
            tabelnya.addColumn("Bagian");
        try{
          koneksi();
          String sql = "Select * From Tb_karyawan";
          ResultSet rs = stat.executeQuery(sql);
          while (rs.next()){
              tabelnya.addRow(new Object []{
                  rs.getString(1),rs.getString(2), rs.getString(3),
              });
          } 
          tblkaryawan.setModel(tabelnya);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Terjadi masalah pada saat load data");
        }            
    }
    
    
    /** Creates new form form2 */
    public form2() {
        initComponents();
        kosong();
        tampil_data();
        setLocationRelativeTo(null);
         btnEdit.setEnabled(false);
         btnSave.setEnabled(true);
         btnHapus.setEnabled(false);
         btnClose.setEnabled(true);
         btnCancel.setEnabled(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtkode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtbagian = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkaryawan = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kode Karyawan");

        jLabel2.setText("Nama Karyawan");

        jLabel3.setText("Bagian");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Delete");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        tblkaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblkaryawan);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtkode, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(txtnama)
                            .addComponent(txtbagian))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtbagian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnClose)
                    .addComponent(btnCancel))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //if ((txtKd_kary.getText().equals(""))||(txtNm_kary.getText().equals(""))||(txtBagian.getText().equals(""))){

        if ((txtkode.getText().equals(""))|| (txtnama.getText().equals(""))||(txtbagian.getText().equals(""))){
        JOptionPane.showMessageDialog(null,"Data Harus Lengkap");
        }else{
            try{
                koneksi();
                String sql = "Select kd_kary FROM tb_karyawan WHERE kd_kary ='" + txtkode.getText() + "'";
                ResultSet rs = stat.executeQuery(sql);
                if (rs.next()){
                    JOptionPane.showMessageDialog(null, "Kode" + txtkode.getText() + "Sudah ada");
                }else{
                    String sqlSave = "INSERT INTO tb_karyawan (kd_kary, nm_kary, bagian) VALUES ('" + txtkode.getText() + "', '" + txtnama.getText() + "', '" + txtbagian.getText() +"')";
                    stat.executeUpdate(sqlSave);
                    tampil_data();
                    kosong();
                    btnEdit.setEnabled(false);
                     btnSave.setEnabled(true);
                     btnHapus.setEnabled(false);
                     btnClose.setEnabled(true);
                     btnCancel.setEnabled(true);

                JOptionPane.showMessageDialog(null,"Data Tersimpan");
                }                        
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Gagal Menyimpan Data");
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int pesan = JOptionPane.showConfirmDialog(null,"Data Akan Dihapus?","Info",JOptionPane.YES_NO_OPTION);
        if (pesan == 0){
            
     
            if ((txtkode.getText().equals(""))|| (txtnama.getText().equals(""))|| (txtbagian.getText().equals(""))){
                JOptionPane.showMessageDialog(null,"Data harus lengkap");
            }else{
                try{
                    String sql = "Delete From tb_karyawan WHERE kd_kary = '" + txtkode.getText() + "'";
                    stat.executeUpdate(sql);
                    tampil_data();
                    kosong();
                    btnEdit.setEnabled(false);
                     btnSave.setEnabled(true);
                     btnHapus.setEnabled(false);
                     btnClose.setEnabled(true);
                     btnCancel.setEnabled(true);

                    JOptionPane.showMessageDialog(null,"Data telah Dihapus");
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Gagal Menghapus data");
                }
        }
        }   
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int pesan = JOptionPane.showConfirmDialog(null,"Keluar Form ?","Info",JOptionPane.YES_NO_OPTION);
        if (pesan == 0){
            System.exit(pesan);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (btnEdit.getText().equals("Edit")){
            btnEdit.setText("Update");
            btnSave.setEnabled(false);
            btnHapus.setEnabled(false);
            btnClose.setEnabled(false);
            btnCancel.setEnabled(true);          
        }else{
            
            try{
                String sql = "Update tb_karyawan SET nm_kary = '" + txtnama.getText() + "', bagian = '" + txtbagian.getText() + "' WHERE kd_kary = '" + txtkode.getText() +"'";
                stat.executeUpdate(sql);
                kosong();
                tampil_data();
                JOptionPane.showMessageDialog(null,"Update Sukses","Info",JOptionPane.INFORMATION_MESSAGE);
                   btnEdit.setText("Edit");
                    btnEdit.setEnabled(false);
                    btnSave.setEnabled(true);
                    btnHapus.setEnabled(false);
                    btnClose.setEnabled(true);
                    btnCancel.setEnabled(true);

            }catch(Exception e){
                JOptionPane.showConfirmDialog(null,"Update Gagal","Warning",JOptionPane.ERROR_MESSAGE);
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        kosong();
        tampil_data();
         btnEdit.setEnabled(false);
         btnSave.setEnabled(true);
         btnHapus.setEnabled(false);
         btnClose.setEnabled(true);
         btnCancel.setEnabled(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkaryawanMouseClicked
        // TODO add your handling code here:
        int tbl = tblkaryawan.getSelectedRow();

        txtkode.setText(tblkaryawan.getValueAt(tbl, 0).toString());
        txtnama.setText(tblkaryawan.getValueAt(tbl,1).toString());
        txtbagian.setText(tblkaryawan.getValueAt(tbl,2).toString());
        btnEdit.setEnabled(true);
        btnSave.setEnabled(false);
        btnHapus.setEnabled(true);
         btnClose.setEnabled(false);
         btnCancel.setEnabled(true);
    }//GEN-LAST:event_tblkaryawanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new form2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblkaryawan;
    private javax.swing.JTextField txtbagian;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
